export const VEGETABLE_LIST_REQUEST = "VEGETABLE_LIST_REQUEST";
export const VEGETABLE_LIST_SUCCESS = "VEGETABLE_LIST_SUCCESS";
export const VEGETABLE_LIST_FAIL = "VEGETABLE_LIST_FAIL";

export const VEGETABLE_FILTER_SEARCH = "VEGETABLE_FILTER_SEARCH";
