export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const SIGNIN_OPEN = "SIGNIN_OPEN";
export const SIGNIN_CLOSE = "SIGNIN_CLOSE";

export const SEND_NAME_REQUEST = "SEND_NAME_REQUEST";
export const SEND_NAME_SUCCESS = "SEND_NAME_SUCCESS";
export const SEND_NAME_FAIL = "SEND_NAME_FAIL";
