export const WISHLIST_CREATE_REQUEST = "WISHLIST_CREATE_REQUEST";
export const WISHLIST_CREATE_SUCCESS = "WISHLIST_CREATE_SUCCESS";
export const WISHLIST_CREATE_FAIL = "WISHLIST_CREATE_FAIL";

export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const WISHLIST_REMOVE_REQUEST = "WISHLIST_REMOVE_REQUEST";
export const WISHLIST_REMOVE_SUCCESS = "WISHLIST_REMOVE_SUCCESS";
export const WISHLIST_REMOVE_FAIL = "WISHLIST_REMOVE_FAIL";
